//LOCALHOST
###
GET http://localhost:8080/contacts/
###
GET http://localhost:8080/contacts/62680fd3e481590b6bb0a8cb
###
GET http://localhost:8080/contacts/62681217e481590b6bb0a8cc
###
GET http://localhost:8080/contacts/6268127ee481590b6bb0a8cd
###
GET http://localhost:8080/
###
GET https://cse341-byuispring2022.herokuapp.com/contacts/
###
GET https://cse341-byuispring2022.herokuapp.com/contacts/62680fd3e481590b6bb0a8cb
###
GET https://cse341-byuispring2022.herokuapp.com/contacts/62681217e481590b6bb0a8cc
###
GET https://cse341-byuispring2022.herokuapp.com/contacts/6268127ee481590b6bb0a8cd
###
POST https://cse341-byuispring2022.herokuapp.com/contacts/ HTTP/1.1 
content-type: application/json

{
    "firstName": "Joey",
    "lastName": "Hasslehoff",
    "email": "hassle@test.com",
    "favoriteColor": "Green",
    "birthday": "10/22/73"
}
###
POST http://localhost:8080/contacts/ HTTP/1.1 
content-type: application/json

{
    "firstName": "Joeyeetee",
    "lastName": "Hasslehoff",
    "email": "hassle@test.com",
    "favoriteColor": "Green",
    "birthday": "10/22/73"
}
###
PUT https://cse341-byuispring2022.herokuapp.com/contacts/6276e5d0680a9f5a7686dee4 HTTP/1.1 
content-type: application/json

{
    "firstName": "Joey",
    "lastName": "Hasslehoffy",
    "email": "hassle@test.com",
    "favoriteColor": "Greeny",
    "birthday": "10/22/73"
}
###
PUT http://localhost:8080/contacts/6276d64ebca3d9e74150cffb HTTP/1.1 
content-type: application/json

{
    "firstName": "Joey",
    "lastName": "Hasslehoffy",
    "email": "hassle@test.com",
    "favoriteColor": "Greeny",
    "birthday": "10/22/73"
}

###
DELETE https://cse341-byuispring2022.herokuapp.com/contacts/6276e5d0680a9f5a7686dee4 HTTP/1.1 

###
DELETE  http://localhost:8080/contacts/6276e5335926e03c693dc4a9 HTTP/1.1 
